### ISSUE TITLE
connecting via socket instead of tcp

### ISSUE THREAD

**Issue by simon-weber** [haraka/haraka-plugin-redis#26]
Using a unix socket instead of tcp is useful for improving performance on same-machine clients. While it's not documented, it does seem possible to connect via a unix socket with a config like:

```
[server]
path=/var/run/redis/redis-server.sock
host=ignored
port=ignored
```

It results in some misleading logging, though:
```
[INFO] [-] [redis] connected to redis://ignored:ignored
```

It might be worthwhile to document this and/or change [how the logging works](https://github.com/haraka/haraka-plugin-redis/blob/fe02b2695dc14fcdb5b6d9f9057777d3fa56711d/index.js#L133-L146).

**Comment by msimerson** [comment]
Indeed, a PR amending the documentation and the log message is welcome.
